[package]
name = "md-resume"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.4.18"
html2pdf = "0.7.0"
markdown = "1.0.0-alpha.16"
